spring:
  cloud:
    gateway:
      routes:
        - id: books-service
          uri: http://localhost:8080
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books(?<segment>.*), /api/books${segment}
            - name: CircuitBreaker
              args:
                name: booksCircuitBreaker
                fallbackUri: forward:/fallback
                